return {
  kind = {
    Text = "",
    Method = "m",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Enum = "ℰ",
    Keyword = "🔑",
    Snippet = "✂️",
    Color = "🎨",
    File = "📄",
    Reference = "",
    Folder = "📁",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "𝙏"
  },
  type = {
    Array = "",
    Number = "#",
    String = "𝓐",
    Boolean = "蘒",
    Object = "",
  },
  documents = {
    File = "",
    Files = "🔬",
    Folder = "",
    OpenFolder = "",
  },
  git = {
    Add = "",
    Mod = "",
    Remove = "",
    Ignore = "",
    Rename = "",
    Diff = "",
    Repo = "🗄️",
  },
  ui = {
    Lock = '🔒',
    Circle = '',
    BigCircle = '',
    BigUnfilledCircle = '',
    Close = '❌',
    NewFile = '📄',
    Search = '🔎',
    Lightbulb = '💡',
    Project = '📁',
    Dashboard = '',
    History = '⌛',
    Comment = '💬',
    Bug = '🐞',
    Code = '',
    Telescope = '🔎',
    -- Telescope = "🔭",
    Gear = "⚙️",
    Package = "📦",
    List = "📝",
    SignIn = "",
    Check = "✔️",
    Fire = "🔥",
    Note = "📝",
    BookMark = "📌",
    Pencil = "✏️",
    ChevronRight = "",
    Table = "",
    Calendar = "📆",
  },
  diagnostics = {
    Error = "⛔",
    Warning = "☢️,",
    Information = "💬",
    Question = "❔",
    Hint = "💡",
  },
  misc = {
    Robot = "🤖",
    Squirrel = "",
    Tag = "🏷️",
    Watch = "🕐",
  },
}
